### PR TITLE
add ffuplink-package to use the routers-wan connection

### PR DESCRIPTION
**Pull request by SvenRoederer**
add a package to use the wan-connection directly (w/o VPN)

### CODE REVIEW

**Comment by bobster-galore** [comment]
It would be nice to have an underhood construction which can be used by any wizard or sthg. to configure the system. Much more which kind of connection could be used.

**Comment by SvenRoederer** [comment]
at the moment branch "packages/notunnel" of the firmware gets build an can then be tested.

**Comment by SvenRoederer** [comment]
one issue with this code is, that the veth-link to the ffuplink interface is setup via a hotplugscript. this should be converted to a uci-setting, as we have patched the lede-17.01 netifd to support this.

**Comment by SvenRoederer** [comment]
This code has been tested and verified to work with 
- OpenVPN-tunnels (at least tested by me)
- direct connection via WAN (see https://lists.berlin.freifunk.net/pipermail/berlin/2017-December/036704.html)
and I'd like to merge it soon.

Probably it's morre elegant to put the uci-setting ffberlin-uplink.uplink.auth directly into network.ffuplink.authtype.

**Comment by SvenRoederer** [comment]
merged into Hedy-1.0.0-rc1

**Comment by SvenRoederer** [comment]
btw: a similar feature seems to be on the way for gluon (https://github.com/freifunk-gluon/gluon/pull/1094)

**Pull request merged**
