### PR TITLE
[olsrd-defaults] set SmartGatewayThreshold=50

### PR DESCRIPTION
**Pull request by andrenarchy**
Without SmartGatewayThreshold being set, the smart gateway endpoint is only
changed when it disappears. With SmartGatewayThreshold=50, it picks
another gateway if its ETX is 50% or less of the current gateway's ETX.

### CODE REVIEW

**Comment by andrenarchy** [comment]
I forgot: this has been tested on several devices. :)

**Comment by booo** [comment]
Can you describe your testing procedure so we can replicate the tests?

**Comment by booo** [comment]
We should add this to the migration script!

**Comment by andrenarchy** [comment]
Test procedure:

1. make sure you have 2 SmartGateways A and B with ETX(A) > 2*ETX(B) in your OLSR mesh (i.e., B is the best gateway based on ETX alone).
2. connect test client with set SmartGatewayThreshold to OLSR mesh.
3. let SmartGateway B disappear -> test node should switch to A.
4. reactivate SmartGateway B -> test node should switch back to B (won't happen without SmartGatewayThreshold).

**Comment by andrenarchy** [comment]
+1 for the migration script! :)

**Comment by booo** [comment]
@andrenarchy are you going to work on this?

**Comment by cholin** [comment]
Merged manually.

**Pull request closed without merging**
