### PR TITLE
[ffwizard] add a note to check all settings after configuration

### PR DESCRIPTION
**Pull request by SvenRoederer**
Inform the user to check the settings done by the assistent. This is
recommended esp. for the WiFi-settings as some there are some routers
that might have incorrect defaults.

### CODE REVIEW

**Comment by SvenRoederer** [comment]
this is somehow related to https://github.com/freifunk-berlin/firmware/issues/381 to make the user aware to operate within legal limits

**Comment by sarumpaet** [comment]
I really dislike such legalese. Also, the link given does not say anything about TX power. If we really want to add something like this, we should give proper advice (including *what* to check for, *how* to check it and *how* to fix it if broken) instead of effectively linking to BNetzA which is not helpful.

**Comment by booo** [comment]
I agree with @sarumpaet and I think this will only create confusion.

@SvenRoederer if you have strong opinions on this please reopen this ticket.

**Comment by SvenRoederer** [comment]
how do you think of a link to the Releasenote?

**Comment by sarumpaet** [comment]
* we'd have to update that link every release
* so far we didn't really write proper release notes ever _really_
* the router/computer is offline when showing the last screen anyways.

**Pull request closed without merging**
