### PR TITLE
network-defaults: disable 802.11b rates by default

### PR DESCRIPTION
**Pull request by SvenRoederer**
to save airtime and avoid client with bad connections
fixes https://github.com/freifunk-berlin/firmware/issues/375

### CODE REVIEW

**Comment by booo** [comment]
This should be part of a wifi package.

What about boards with multiple wifi interfaces?

As far as I know our current wifi configuration is part of the wizard. Maybe we should move this to the wizard code or move the code from the wizard to a default-script?

**Comment by SvenRoederer** [comment]
what about adding it to the Community-profile?

**Comment by SvenRoederer** [comment]
what about adding it to the Community-profile? 
There are already the Channels BSSIDs and other stuff defined.

**Comment by booo** [comment]
Sounds like a plan. But I guess we still have to make a minor change to our scripts for this.

**Comment by bobster-galore** [comment]
What are the necessary changes to our scripts? community profile sounds like the right place so any community can adjust to its own demand.

**Comment by bobster-galore** [comment]
@SvenRoederer and me discussed the topic regarding reading community profile and let a wizard transfer the values. Since there is nothing prepared yet for a wizard and no solution visible for backbone images, we suggest to switch off 802.11b via the network-defaults-package. 
It will be documented w/ the release notes and the wiki.

**Comment by SvenRoederer** [comment]
can anyone test this code on a 5GHz-router and on a dual-band?
I don't have access to any of these

**Comment by SvenRoederer** [comment]
just for reference: the "legacy_rates" option will not cause any change or error on 5GHz-radios

**Comment by SvenRoederer** [comment]
I close this PR in favor of https://github.com/freifunk-berlin/firmware/pull/499

**Pull request closed without merging**
