### PR TITLE
rearrange tree

### PR DESCRIPTION
**Pull request by SvenRoederer**
Move some packages into separate directories, to group them meaning-wise
  * separate directory for the default-files
  * separate directory for addons and libs
  * keep utils for the rest

Having just a utils-subdirectory looks somehow ugly

### CODE REVIEW

**Comment by booo** [comment]
Can you post the tree here. It's hard to see the actual tree structure in the github interface.

In general I'm fine with the idea. Maybe we should use plural for e.g. the addon directory? Should we remove freifunk-berlin from the subdirectories?

**Comment by SvenRoederer** [comment]
after changing to "addons" it would look like this:
```
./defaults/freifunk-berlin-dhcp-defaults
./defaults/freifunk-berlin-freifunk-defaults
./defaults/freifunk-berlin-network-defaults
./defaults/freifunk-berlin-uhttpd-defaults
./defaults/freifunk-berlin-statistics-defaults
./defaults/freifunk-berlin-openvpn-files
./defaults/freifunk-berlin-firewall-defaults
./defaults/freifunk-berlin-olsrd-defaults
./utils/freifunk-berlin-wizard-frontend
./utils/luci-app-ffwizard-berlin
./utils/luci-app-owm
./utils/freifunk-berlin-statistics-defaults_bkuup
./utils/freifunk-berlin-migration
./utils/freifunk-berlin-meta
./utils/freifunk-berlin-wizard-backend
./utils/luci-mod-freifunk-ui
./utils/freifunk-berlin-policy-routing
./addons/freifunk-berlin-lib-guard
./addons/collectd-addons
```

**Comment by SvenRoederer** [comment]
any comments?

**Comment by booo** [comment]
I think it's fine. Feel free to merge.

**Pull request merged**
