### PR TITLE
 lua-app-owm: adapt code to new wifinets and wifidevs api

### PR DESCRIPTION
**Pull request by booo**
The upstream api for accessing wifidevs and wifinets changed. This adapts the code to the new code base and fixes:

freifunk-berlin/firmware#435

Tested. Seems to work. Example is: http://openwifimap.net/#detail?node=refugees-fritzreuter.olsr

### CODE REVIEW

**Comment by SvenRoederer** [comment]
what about squashing some commits, like "removing dead code", "removing unused vars" ... ?

So many micro-commits

**Comment by booo** [comment]
I think the commits are fine as they are. Most of them contain a description that belongs to the specific commit. I don't want to loose the context by squashing the commits.

**Comment by SvenRoederer** [comment]
This might supersede #108

**Comment by SvenRoederer** [comment]
tested on CPe210 & wr1043v2

**Comment by booo** [comment]
Thanks for testing!

**Pull request merged**
