### PR TITLE
Hedy 1.0.x: backport tunneldigger

### PR DESCRIPTION
**Pull request by SvenRoederer**
This backports all tunneldigger relevant packages from master-branch. 
* tunneldigger package
* tunnelberlin_tunneldigger uplink-package
* tunneldigger bbbvpn-connection

This collects all relevant commits in a individual branch that can be merged

The commits are authored by @pmelange

### CODE REVIEW

**Comment by SvenRoederer** [comment]
@pmelange I would prefer, that you add this branch on to of the "for-Hedy-1.0.x_change_uplink" branch, as the tunneldigger-branch needs less rebasing and is younger.
I assume we want to provide an upgrade-path for VPN03 --> x.

**Comment by pmelange** [comment]
Well, the merge created a lot of chaos in the commit log.  But the code looks correct.

**Comment by SvenRoederer** [comment]
not sure why you did 724007a4f2e18c36d0b50fc0d1212feed7551109? this pulls a lot of commits and causes the hassle, but results in no difference of the code.
merging my workingtree of this (6227b472db1313a6fa646c90f2bd620dcdb26588) works like a charm.

**Comment by pmelange** [comment]
So, can we delete the for-Hedy-1.0.x-tunneldigger branch and continue working on for-Hedy-1.0.x from here?

**Comment by SvenRoederer** [comment]
As you did not gave the intention behind 724007a I'll clean this commits-mess.

As you preferred to break my "for-Hedy-1.0.x_change_uplink" branch, it looks like we have to do so.

**Comment by SvenRoederer** [comment]
fixed commit-log chaos in for-Hedy-1.0.x branch by f47d13451

**Comment by SvenRoederer** [comment]
@pmelange  as you also put 5bca8e3670ecd8587cf6cb4468ded67b39000ac9 in the middle of this backport, we also need a migration for this

**Comment by pmelange** [comment]
The original migration commit is 355428c00f47b81f4a534b61087299ac8ece3c3c.  I will work on a commit for 1.0.2 and a seperate commit to revert the version for 1.1.0.

**Comment by SvenRoederer** [comment]
for now, I would not work on a revert on the master-branch. let's postpone this, till this it released

**Pull request merged**
