### PR TITLE
freifunk-berlin-freifunk-defaults: use uci-default script

### PR DESCRIPTION
**Pull request by booo**
The freifunk-common package provides the same configuration file as the
freifunk-berlin-freifunk-defaults package. Therefore we use a
uci-defaults script to overwrite the configuration from freifunk-common
on the first boot of the router.

### CODE REVIEW

**Comment by SvenRoederer** [comment]
what about this: https://github.com/SvenRoederer/freifunk-berlin-firmware-packages/tree/SAm0815/freifunk-defaults

**Comment by booo** [comment]
As far as I remember there is a lot of junk in the configuration file **we** don't need. I would prefer a lean configuration file.

Taking the upstream file and modifying it is probably better. But for this I think we have to change the content of the upstream file first.

What about restoring the old behaviour with this pull request and fixing the overall problem later on in the process?

**Comment by SvenRoederer** [comment]
to rethink for the next release is probably the best option to choose.

but the points to review still needs to be fixed / ironed out

**Comment by booo** [comment]
I don't get what you mean with "still needs to be fixed/ironed out".

**Comment by SvenRoederer** [comment]
> I don't get what you mean with "still needs to be fixed/ironed out".

the points to review I meintioned above

**Comment by booo** [comment]
Which points?

**Comment by booo** [comment]
I'm merging this to restore the old behaviour.

Please open another pull request if you want to improve on the configuration.

**Pull request merged**
