### PR TITLE
Hedy 1.0.x: integrate tunneldigger into change_uplink

### PR DESCRIPTION
**Pull request by SvenRoederer**
This PR shows what needs to be done when merging all importent features of Hedy-1.0.2 together

### CODE REVIEW

**Comment by pmelange** [comment]
This needs to be looked at again.  Many commits are doubled

**Comment by SvenRoederer** [comment]
There have been just 6 commits, which looked very clean for me. but after merging the tunneldigger-stuff into for-Hedy-1.0.x branch, we have to go the more complicated way by merging the change_uplink stuff  onto the now integrated tunneldigger-stuff.

**Comment by pmelange** [comment]
Is there a way that we can divide the work?  And from the message above, it looks like only the notunnel stuff has the conflict.

**Comment by SvenRoederer** [comment]
@pmelange  please check for 
* the conflict in `uplinks/freifunk-berlin-uplink-no-tunnel/uci-defaults/freifunk-berlin-notunnel`
* ensure that the previously merged tunneldiggerstuff (uplink-package) meets the current style of the other uplink-packages

I'll rebase the code, and squash some commits.

**Comment by pmelange** [comment]
The conflicting code for the notunnel changes have been moved into a seperate PR #167

**Comment by SvenRoederer** [comment]
@pmelange just sen that you had 5bca8e3670ecd8587cf6cb4468ded67b39000ac9 in your tunneldigger-backport, which was causing the merge-conflict.

To avoid such merge-conflicts I split this off of the "merge tunneldigger"-PR on master branch.

**Comment by pmelange** [comment]
Is this a replacement for #159?

**Pull request merged**
